
import { Course, CourseLevel } from './types';

export const MOCK_COURSES: Course[] = [
  {
    id: 1,
    title: 'Fundamentals of Chess',
    coach: { name: 'Anna Rudolf', rating: 4.8 },
    level: CourseLevel.BEGINNER,
    price: 10,
    duration: '4 weeks',
    language: 'English',
    imageUrl: 'https://picsum.photos/seed/chess1/400/300',
  },
  {
    id: 2,
    title: 'Mastering the Sicilian Defense',
    coach: { name: 'Levon Aronian', rating: 4.9 },
    level: CourseLevel.INTERMEDIATE,
    price: 25,
    duration: '6 weeks',
    language: 'English',
    imageUrl: 'https://picsum.photos/seed/chess2/400/300',
  },
  {
    id: 3,
    title: 'Advanced Endgame Strategies',
    coach: { name: 'Judit Polgár', rating: 5.0 },
    level: CourseLevel.ADVANCED,
    price: 45,
    duration: '8 weeks',
    language: 'English',
    imageUrl: 'https://picsum.photos/seed/chess3/400/300',
  },
  {
    id: 4,
    title: 'Pro-Level Opening Theory',
    coach: { name: 'Magnus Carlsen', rating: 5.0 },
    level: CourseLevel.PRO,
    price: 99,
    duration: '10 weeks',
    language: 'English',
    imageUrl: 'https://picsum.photos/seed/chess4/400/300',
  },
  {
    id: 5,
    title: 'The Art of Attack',
    coach: { name: 'Mikhail Tal', rating: 4.9 },
    level: CourseLevel.INTERMEDIATE,
    price: 30,
    duration: '5 weeks',
    language: 'English',
    imageUrl: 'https://picsum.photos/seed/chess5/400/300',
  },
  {
    id: 6,
    title: 'Beginner Tactics & Puzzles',
    coach: { name: 'GothamChess', rating: 4.7 },
    level: CourseLevel.BEGINNER,
    price: 15,
    duration: '3 weeks',
    language: 'English',
    imageUrl: 'https://picsum.photos/seed/chess6/400/300',
  },
];
